
language: clojure
lein: 2.6.1
sudo: required # Workaround: https://github.com/travis-ci/travis-ci/issues/4691

script:
  - lein test
  - lein kibit

after_success:
  - CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
